### ISSUE TITLE
Workflow/To-do

### ISSUE THREAD

**Issue by jcha1997** [kuriwaki/cces_candidates#39]
Shiro

- [ ] Validate president results against Brookings presidential results 1990-2006
- [ ] Validate gubernatorial results against Brookings presidential results 1990-2006
- [ ] Combine fusion candidates NY and CT 1990-2006

Jeremiah 
- [ ] Validate House candidate names by Congress (e.g. use incumbency to check names) 
- [ ] Validate Senate candidate names by Congress
- [ ] Split datasets (e.g. special v. general)
